### ISSUE TITLE
ngrinder 시작오류 - 헤더와 쿠키 그리고 동시성 문제

### ISSUE THREAD

**Issue by temp12312yeap** [beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project#13]
인원수에 상관없이 50초정도를 버티고 connection이 refused됩니다. 
에러에는 처음 헤더와 쿠키의 문제 그리고 동시성 문제가 발생하고 있습니다.. 문제가 뭘까요...?
2024-02-28 17:11:46,994 INFO  before. init headers and cookies
2024-02-28 17:11:46,995 ERROR java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
java.net.ConnectException: Connection refused
	at org.apache.hc.core5.reactor.InternalConnectChannel.onIOEvent(InternalConnectChannel.java:64)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:179)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:128)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:85)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)

**Comment by pySatellite** [comment]
같이 살펴 봅시다. 동시성 문제로 생각하신 이유도 궁금합니다.

**Comment by temp12312yeap** [comment]
![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_4nd_mini-project/assets/157056836/bdc9038e-9d31-470b-b3f2-0150dd871f0b)
java에서의 GC 설정을 바꿔주거나 혹은 에러가 뜨더라도 해당 설정 시간동안 계속 ngrinder가 지속되게 하여 물결모양의 결과를 가질 수 있음.  

현 프로젝트에서는 proxy설정을 통해 문제해결가능 - 많은 요청중 e.g. - 90% 이상 차지하는 동일한 요청을 proxy에서 처리해 요청자에게 바로 반환해주는 형태(app - db로 가지 않고 proxy에서 처리) = 캐싱처리
